### ISSUE TITLE
Cannot compile modules unless the '--module' flag is provided

### ISSUE THREAD

**Issue by ibrahimkais** [Steve-Fenton/tsUnit#12]
I'm using vs 2015 community. after installation I got this error.
Error	TS1148	Cannot compile modules unless the '--module' flag is provided.

**Comment by Steve-Fenton** [comment]
Version 2.0 comes with a caveat...

NOTE: Version 2.0 has breaking changes, to improve re-use between different module systems. Please read the below to see how to use version 2.0.

This means that from v2.0 onwards, tsUnit is fully committed to supporting module systems. All of the examples show how to jump straight into this way of working. For web pages, the examples use RequireJS and for NodeJS the examples use the built in module system.

Please shout if you need help using modules - or switch to the pre-version-2 version of tsUnit (either by grabbing the earlier version from your preferred package manager or by browsing https://github.com/Steve-Fenton/tsUnit/tree/134e56c51a9e20a3bef62fc4c8fcaf6096b818a4)
