### ISSUE TITLE
Does tsUnit contain anything for mocking ajax calls?

### ISSUE THREAD

**Issue by beradrian** [Steve-Fenton/tsUnit#13]
I'm looking for something similar to http://jasmine.github.io/2.0/ajax.html.

**Comment by Steve-Fenton** [comment]
There is nothing specific in tsUnit for mocking AJAX calls. You could use an additional library for this if needs be. For example, if you are using a library for AJAX calls, there is usually a mocking library available specifically for it.

I'm happy to consider a very general AJAX mock, but it would need to be useful in the widest number of cases to be worth adding to tsUnit.

**Comment by Steve-Fenton** [comment]
Also see #16 regarding async support.

**Comment by Steve-Fenton** [comment]
See https://github.com/testdouble/testdouble.js

Perhaps this is a better option than trying to add it into tsUnit.
