### ISSUE TITLE
Problem when calling TestClass.parameterizeUnitTest multiple times

### ISSUE THREAD

**Issue by KoenT-IM** [Steve-Fenton/tsUnit#14]
We have unit test code as follows:

```
import * as tsUnit from "Scripts/tsUnit/tsUnit";
import Utilities = require("Utilities");

export class MyTests extends tsUnit.TestClass
{
    parameterizedTests()
    {
        // Frist group of parameters to be tested
        this.parameterizeUnitTest(this.testMySpecialFunction,
            [
                [0, true],
                [-1.1, false],
            ]);

        // Second group of parameters to be tested
        this.parameterizeUnitTest(this.testMySpecialFunction,
            [
                [-1, true],
                [1, true],
            ]);
    }

    private testMySpecialFunction(value: number, expectedResult: boolean)
    {
        this.areIdentical(expectedResult, Utilities.mySpecialFunction(value));
    }
}

```

This is a simple example, and splitting up the various test parameter sets might not make much sense here, but we sometimes have more complicated tests where it makes sense to split up test cases for a particular function into different groups of parameter sets.

The _problem_ is that when you currently run this, only the last set of parameters is being used, and the first set is never tested at all. We noticed this after seeing that some tests never failed (even if you used garbage parameters).

The reason for this is as follows:
in tsUnit.ts line 517 and following, there is:

```
export class TestClass extends TestContext {
    protected parameterizeUnitTest(method: Function, parametersArray: any[][]) {
        (<any>method).parameters = parametersArray;
    }
}
```

So, what happens is that when you call parameterizeUnitTest a second time (after having parameterized a test earlier), the previous sets of parameters get overwritten by the last one.

--> Could this be changed, so that a new array of parameters gets added/appended to the existing one, instead of overwriting the existing parameters array?

**Comment by Steve-Fenton** [comment]
Hello,

The intended usage didn't include this case.

It is very common to want to group sets of test cases in a parametrised test. This is usually achieved by having one test method per group.

If you desperately want to avoid multiple methods, you could submit a pull request to change the behaviour as it won't affect other users.

**Comment by KoenT-IM** [comment]
OK.
We made it one test method per group now. It's a bit less structured, but works. We'll see if the need re-occurs, and if so provide a patch.

**Comment by Steve-Fenton** [comment]
Okay - thank you.
