### ISSUE TITLE
No tests found with es6 target

### ISSUE THREAD

**Issue by jbrownson** [Steve-Fenton/tsUnit#17]
I'm testing using Chrome 49.

If you set your target to ES6 all of your tests disappear.

`for (var unitTestName in testClass) {`
in ES6 none of the functions are returned in the `for`. I'm not much of a javascript guy and I tried a quick google to see if this is something folks are talking about and came up dry, but I did some tests myself and found that to be the case.

To be clear I'm not talking about transpiling, just using raw ES6.

I noticed this when I switched my project to use ES6 for unrelated reasons and my tests all stopped showing up.

**Comment by jbrownson** [comment]
Found these:
http://stackoverflow.com/questions/31423573/how-to-enumerate-es6-class-methods
http://stackoverflow.com/questions/31054910/get-functions-methods-of-a-class

**Comment by jbrownson** [comment]
Worked around this and looks like it goes deeper too, you can't use `apply` to call an ES6 constructor.

**Comment by Steve-Fenton** [comment]
:+1: 

I will look at this issue shortly, thanks for flagging it.

**Comment by wmelani** [comment]
Created for https://github.com/Steve-Fenton/tsUnit/pull/24 with a fix for this.

**Comment by Steve-Fenton** [comment]
Package 2.0.9 is now available with this awesome change.

    <releaseNotes>
        ES2015 compatibility (Will Melani)
    </releaseNotes>
