### ISSUE TITLE
Error runing your sample

### ISSUE THREAD

**Issue by stevegray12** [Steve-Fenton/tsUnit#18]
Whne I build and run your sample app I get in the browser?

require.js:140 Uncaught Error: Module name "Scripts/tsUnit/tsUnit" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded

**Comment by Steve-Fenton** [comment]
Hello, the project was using the previous version of the tsUnit NuGet package. I am updating it to use the latest one now (which uses the UMD module style so the same file works in browsers and on node.js).

**Comment by Steve-Fenton** [comment]
Should be all fixed. Let me know if you have any other problems.

**Comment by stevegray12** [comment]
Works now, many thanks,
