### ISSUE TITLE
No TestAsync class in the NuGet package?

### ISSUE THREAD

**Issue by john-cronan** [Steve-Fenton/tsUnit#23]
I'm referencing 2.0.3 via NuGet, and I'm not seeing a TestAsync class. Everything I've read here leads me to expect it there. Is there another package for async testing or something?

**Comment by Steve-Fenton** [comment]
Hello,

Can you try getting the latest package on NuGet (2.0.6) and see if you can get what you need?

Thanks.

**Comment by john-cronan** [comment]
Thanks, Steve. But looks like the 2.0.6 package doesn't have it either.

**Comment by Steve-Fenton** [comment]
I can see the problem. It needs to be added to the files section in the nuspec file. 2.0.10 has it. Sorry.
