### ISSUE TITLE
npm not updated with es2015 fix

### ISSUE THREAD

**Issue by dabbers** [Steve-Fenton/tsUnit#25]
NPM hasn't been updated with the fix for support for es2015, and the packages.json (in GitHub) still lists it as 2.0.9.

**Comment by Steve-Fenton** [comment]
Hello dabbers. I have published 2.0.10 - I have inspected the package and I can see `FunctionPropertyHelper` in there, which is the ES6/ES2015 update. Can you confirm you can see it in there?

**Comment by dabbers** [comment]
Yep it looks to be updated now. Thanks!
