### ISSUE TITLE
Error in README related to getTapResults usage example

### ISSUE THREAD

**Issue by jimsugg** [Steve-Fenton/tsUnit#26]
Readme currently shows this code:
var tap = new tsUnit.Test(CalculationsTests).getTapResults();

It should be:
var tap = new tsUnit.Test(CalculationsTests).run().getTapResults();

Pretty minor, but confused me for a few minutes...

Thanks.

**Comment by Steve-Fenton** [comment]
Thanks Jim - I have updated the example, so thank you for pointing it out and saving the next developer some time :)
