### ISSUE TITLE
tsUnit.Examples failes

### ISSUE THREAD

**Issue by mberickson** [Steve-Fenton/tsUnit#28]
I load project "tsUnit.Examples" into VS 2015, open file "default.htm", and start without debugging. I get a Webpage Error as follows:

Line: 13
Error: Unable to get property 'Test' of undefined or null reference

Suspect software needs some work.

Thanks

**Comment by Steve-Fenton** [comment]
It is worth making sure you have compiled the TypeScript first, as I don't check the JavaScript into the repository (i.e. https://github.com/Steve-Fenton/tsUnit/tree/master/tsUnit.Examples/Scripts)

The HTML file references the JavaScript files, which only appear once TypeScript has run to generate them.

Thanks
