### ISSUE TITLE
Compiling problems

### ISSUE THREAD

**Issue by tingdahl** [Steve-Fenton/tsUnit#29]
Hi,

I have installed tsUnit using

npm install tsunit.external

but I get an error when running the simplest file: Already at the import, it fails with the error:

node_modules/tsunit.external/tsUnit.ts(579,40): error TS2304: Cannot find name 'Set'.
node_modules/tsunit.external/tsUnit.ts(595,29): error TS2304: Cannot find name 'Set'.
node_modules/tsunit.external/tsUnit.ts(597,22): error TS2339: Property 'from' does not exist on type 'ArrayConstructor'.

I guess that there are some definitions missing? but what? Have I omitted something?

Cheers,

Kristofer

**Comment by drew212** [comment]
I am also seeing this issue along with a few others when trying to compile my tests.

**Comment by Steve-Fenton** [comment]
Hello,

The ```Set``` interface comes from lib.es6.d.ts.

I'm using Visual Studio and this is part of the "standard" library of definitions found in:

    C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript

There is also a [version on GitHub in the TypeScript project](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts).

Does this help with your issue?

**Comment by tingdahl** [comment]
Steve,

Thanks for looking into this!

I have to test that out, but I don't have the time right now. From what you
wrote, I think that will fix the issue.


Cheers,


Kristofer

2017-02-02 9:16 GMT+01:00 Steve Fenton <notifications@github.com>:
