### ISSUE TITLE
failing async tests throw error - testing stops and no results are shown

### ISSUE THREAD

**Issue by flyon** [Steve-Fenton/tsUnit#30]
When running async tests and one test fails, testing stops, and results are not shown.
A simplified version of my setup:

    export default class AsyncTest extends tsUnit.TestClass
    {
        testAsync()
        {
        	return new Promise((resolve,reject) => {
        		this.isTrue(false);
        	});
        }
    }
---
    tsUnit.ts:499 Uncaught (in promise) Error: isTrue failed when given {boolean} "false"
        at AsyncTest.getError (tsUnit.ts:499)
        at AsyncTest.isTrue (tsUnit.ts:404)
        at AsyncTest.testAsync (AsyncTest.ts:15)
        at Promise.resolve.then (tsUnitAsync.ts:119)

this.setState is never called:

    var testAsync = new TestAsync({AsyncTest});
    testAsync.runAsync().then(resultAsync => {
        this.setState({resultAsync:resultAsync});

**Comment by hn3000** [comment]
You're not showing how you import that AsyncTest, but the "export default" looks suspicious to me. I tried to reproduce your test case and I get an exception thrown in the constructor of TestAsync ...

**Comment by hn3000** [comment]
Did you solve the problem? Can the issue be closed?

**Comment by Steve-Fenton** [comment]
Thanks for popping this one back on the radar @hn3000 👍 

The assertion library throws an exception when an assertion fails. When wrapping that in a promise, you'll need to handle the exception.

Your "then" won't be called because there is an error. When working with promises, it is best to anticipate an error...

```
var testAsync = new TestAsync({AsyncTest});
testAsync.runAsync()
    .then((resultAsync) => { this.setState({resultAsync:resultAsync})
    .catch((err) => { alert(err); });
```

Also, your "then" is expecting a value, but your promise doesn't return one... so maybe you could just return the result of the comparison?

```
    	return new Promise((resolve,reject) => {
    		return true === false;
    	});
```

**Comment by hn3000** [comment]
That's a good demonstration of why the Promise constructor should be avoided -- the only way to resolve the promise is to call `resolve`, if you want it to fail you must call `reject`.

A good pattern to avoid this pitfall is to use resolve and then write your code in the first `then`:

    export default class AsyncTest extends tsUnit.TestClass
    {
        testAsync()
        {
            return Promise.resolve().then(function () {
                this.isTrue(false)
            });
        }
    }

And looking at the extract above, I think the TestRunner might need to use that pattern, too ...

**Comment by Steve-Fenton** [comment]
At the moment the architecture is callback-heavy. We could add an enhancement issue to move things over to a promise-based API... but it is probably best done in a new major version (which we could start straight away as there are no other changes on the cards right now). It depends a little on how much you feel the callbacks are exposed externally.

**Comment by hn3000** [comment]
+1 for the enhancement issue
