### ISSUE TITLE
Build errors in Visual Studio

### ISSUE THREAD

**Issue by danieltulp** [Steve-Fenton/tsUnit#35]
Working with Visual Studio 2017 community edition
TypeScript version 2.8.4
tsUnit NuGet package version 2.0.11
ASP.NET version 4.6.1

When I try to build my application I get the following errors:

>     Error TS2304: Build:Cannot find name 'Set'. (579, 40)
>     Error TS2304: Build:Cannot find name 'Set'. (579, 40)
>     Error TS2304: Build:Cannot find name 'Set'. (595, 29)
>     Error TS2304: Build:Cannot find name 'Set'. (595, 29)
>     Error TS2339: Build:Property 'from' does not exist on type 'ArrayConstructor'. (597, 22)
>     Error TS2339: Build:Property 'from' does not exist on type 'ArrayConstructor'. (597, 22)
>     Error TS2693: Build:'Promise' only refers to a type, but is being used as a value here. (103, 16)
>     Error TS2693: Build:'Promise' only refers to a type, but is being used as a value here. (103, 16)
>     Error TS2693: Build:'Promise' only refers to a type, but is being used as a value here. (114, 16)
>     Error TS2693: Build:'Promise' only refers to a type, but is being used as a value here. (114, 16)

**Comment by Steve-Fenton** [comment]
There is probably a wider task here to upgrade tsUnit from TypeScript 1.8 (as it hasn't been updated for a while). Can you try the 2.1.0 version pushed to NuGet to see if it resolves it, it uses TypeScript 2.8 (tentatively).

**Comment by danieltulp** [comment]
With 2.1.0 I get the same errors:

>     Error TS2304: Build:Cannot find name 'Set'. (579, 40)
>     Error TS2304: Build:Cannot find name 'Set'. (579, 40)
>     Error TS2304: Build:Cannot find name 'Set'. (595, 29)
>     Error TS2304: Build:Cannot find name 'Set'. (595, 29)
>     Error TS2339: Build:Property 'from' does not exist on type 'ArrayConstructor'. (597, 22)
>     Error TS2339: Build:Property 'from' does not exist on type 'ArrayConstructor'. (597, 22)
>     Error TS2693: Build:'Promise' only refers to a type, but is being used as a value here. (103, 16)
>     Error TS2693: Build:'Promise' only refers to a type, but is being used as a value here. (103, 16)
>     Error TS2693: Build:'Promise' only refers to a type, but is being used as a value here. (114, 16)
>     Error TS2693: Build:'Promise' only refers to a type, but is being used as a value here. (114, 16)

**Comment by danieltulp** [comment]
I found a gitHub issue that is related to this error?
https://github.com/Microsoft/TypeScript/issues/3069

**Comment by danieltulp** [comment]
Aah, I figured out from this post 
https://github.com/Microsoft/TypeScript/issues/3069#issuecomment-368982656 
that I had to target es6 in my tsconfig instead of es6

can you support es5?

**Comment by danieltulp** [comment]
Perhaps this can help you:
https://github.com/paulmillr/es6-shim

**Comment by Steve-Fenton** [comment]
Ah - ES5 is supported in 2.0.10 - I don't think we'll be supporting it in later versions - but from a feature perspective you won't lose anything on 2.0.10. Let me know if you have any problems with that version.
