### ISSUE TITLE
NPM install command not displayed in README

### ISSUE THREAD

**Issue by frederic-danna** [Steve-Fenton/tsUnit#36]
In the README file, the command for installing via NPM is not displayed when MarkDown is rendered int o HTML.

This is because the tripe-back-quotes are not closed.

**Comment by stealthrabbi** [comment]
FYI, the raw Readme file shows:

`npm i tsunit.external`

**Comment by Steve-Fenton** [comment]
@frederic-danna @stealthrabbi 

Thank you both for spotting this one. The code block has now been fixed!
