### ISSUE TITLE
HashChangeEvent not found

### ISSUE THREAD

**Issue by dlaub123** [Steve-Fenton/tsUnit#6]
I can't compile tsUnit w/o getting multiple errors: 
Error	1	Cannot find name 'HashChangeEvent'.	C:\Users\laubd\Downloads\tsUnit-master\tsUnit-master\tsUnit.Node.Examples\node_modules\tsunit.external\tsUnit.ts	256	49	tsUnit.Node.Examples

**Comment by Steve-Fenton** [comment]
I'm guessing that you are using TypeScript 1.4 or earlier - there was a change in ```lib.d.ts``` in TypeScript 1.5 that means the ```HashChangeEvent``` is now the correct type.

If you are using TypeScript 1.4, you can grab the snapshot of tsUnit that was written in 1.4:

https://github.com/Steve-Fenton/tsUnit/tree/c63153bbdff934efa01c86ec639487a96c1343fd

I will also quickly check this out before closing the issue in case something else is causing the problem.

Thanks

**Comment by dlaub123** [comment]
Thanks - I'm using VS 2103 - so whatever version that uses...I'm guessing
1.4

**Comment by Steve-Fenton** [comment]
You can check by typing the following into command prompt:

```tsc -v```

You can get the updated VS2013 tools here:

https://visualstudiogallery.msdn.microsoft.com/107f89a0-a542-4264-b0a9-eb91037cf7af

TypeScript 1.5 is excellent :)

**Comment by dlaub123** [comment]
will do - thanks!!
