### ISSUE TITLE
Ignore internal/private functions from Test classes

### ISSUE THREAD

**Issue by ccvca** [Steve-Fenton/tsUnit#7]
How to exclude (internal) functions from a test class?
Currently _doPrepare() will also execute as a Test.
```javascript
module Tests {
	export class DummyTest extends tsUnit.TestClass{
		private _doPrepare(i:number) {
			//Prepare the class with 'i'
		}
		public checkOne() {
			this._doPrepare(5);
			this._doPrepare(7);
			this.isTrue(this.internal);
		}
		public checkTwo() {
			this._doPrepare(5);
			this._doPrepare(8);
			this.isFalse(this.internal);
		}
	}
}
```
Maybe ignore all functions that start with a '_' (or a predefined RegEx Pattern), or add a function for adding functions that should be ignored.

**Comment by Steve-Fenton** [comment]
This is a really good suggestion. I think adhering to the JavaScript convention of '_' prefixed methods for privacy is a sensible route - perhaps with a way to adjust the behaviour if people want to.

**Comment by Steve-Fenton** [comment]
Added in v1.9.0 - now available on NuGet.

https://www.nuget.org/packages?q=tsunit
